import { BaseCube } from "./cubes/BaseCube.js"

const APP = document.querySelector('#app')

const cube = new BaseCube(APP)

cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()
cube.render()